### ISSUE TITLE
Question : How good is this project for production usage?

### ISSUE THREAD

**Issue by gabdu** [jedisct1/vtun#1]
Very interesting enhancements to vtun. I dont see any commits lately hence the question.

**Comment by jedisct1** [comment]
If you really want to use vtun, I'd highly recommend using this fork instead. It's a little less terrible than the original vtun.

But there are way better options these days. Namely Glorytun, Wireguard and MLVPN.

**Comment by gabdu** [comment]
Thanks for the quick reply. I would not use vtun in production hence
looking for a more secure replacement. Wireguard, I cant use since this
requires loading of a kernel module on production server. Let me check out
glorytun and MLVPN.

**Comment by jedisct1** [comment]
And to answer your original question, it should be fine for production usage. This was originally written to be embedded in load-balancing appliances sold by OVH. But it was eventually replaced with Glorytun, whose performance is excellent.

**Comment by gabdu** [comment]
Cool thanks. Glorytun does seem to come with a bunch of disclaimers though!
Moreover it seems to be TCP only, in intend to use a lightweight VPN to
actually inject packets over it, more like a soft network tap. Wouln't
glorytun run into tcp over tcp issues?

**Comment by jedisct1** [comment]
Glorytun was specifically designed to avoid tcp over tcp issues, and it's the only VPN software I know of that does it.

Check out the "mud" branch.

Both have been and are still used in production.
